image: elavram/ubuntu:latest

stages:
  - build
  - test

build:ubuntu:
  stage: build
  tags:
    - docker
  script:
    - cd /builds/$CI_PROJECT_PATH
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Release -DENABLE_EXAMPLES=ON -DENABLE_TESTS=ON ..
    - make
  artifacts:
    paths:
      - build

test:ubuntu:
  stage: test
  tags:
    - docker
  script:
    - cd /builds/$CI_PROJECT_PATH/build
    - ctest