image: elavram/ubuntu:latest

stages:
  - build
  - test

build:ubuntu:
  stage: build
  tags:
    - docker
  script:
    - cd /builds/$CI_PROJECT_PATH
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Release -DCHRONOS_ENABLE_EXAMPLES=ON -DCHRONOS_ENABLE_TESTS=ON ..
    - make
  artifacts:
    paths:
      - build

test:ubuntu:
  stage: test
  tags:
    - docker
  script:
    - cd /builds/$CI_PROJECT_PATH/build
    - ctest