image: elavram/ubuntu:latest

stages:
  - build
  - test

build:ubuntu:
  stage: build
  tags:
    - docker
  script:
    - apt-get update && apt-get install -y build-essential wget libssl-dev
    - mkdir cmake
    - wget https://github.com/Kitware/CMake/releases/download/v3.16.0/cmake-3.16.0.tar.gz
    - tar -xf cmake-3.16.0.tar.gz
    - cd cmake-3.16.0
    - ./bootstrap
    - make install
    - cd /builds/$CI_PROJECT_PATH
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Release -DENABLE_EXAMPLES=ON -DENABLE_TESTS=ON ..
    - make
  artifacts:
    paths:
      - build

test:ubuntu:
  stage: test
  tags:
    - docker
  script:
    - apt-get update && apt-get install -y build-essential cmake
    - cd /builds/$CI_PROJECT_PATH/build
    - ctest