image: Visual Studio 2019

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - mkdir build
  - cd build
  - cmake  -DCHRONOS_ENABLE_EXAMPLES=ON -DCHRONOS_ENABLE_TESTS=ON ..
  - cmake --build . --target ALL_BUILD --config Release

test_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - cd build
  - ctest -C Release