image: Visual Studio 2019

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build . --target ALL_BUILD --config Release -DENABLE_EXAMPLES=ON -DENABLE_TESTS=ON

test_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - cd build
  - ctest -C Release